version: '3.3'

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    env_file:
      - .env
    container_name: "sqlserver"
    ports:
      - "1433:1433"
    volumes:
      - ./database/mssql/:/var/opt/mssql
    networks:
      - local
networks:
  local:
    driver: bridge