version: "3.3"

services:
  # sqlserver for databases
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "City@1234"
      ACCEPT_EULA: "Y"
    container_name: "sqlserver"
    ports:
      - "1433:1433"
    networks:
      - local
    restart: always
    volumes:
      - sqlserver_data:/var/opt/mssql

networks:
  local:
    driver: bridge

volumes:
  sqlserver_data:
